[build]
  publish = "dist"
  command = "pnpm run build"

[[redirects]]
  from = "/"
  to = "https://lukastrumm.com/talks"
  status = 302

[[redirects]]
  from = "/2024-web-performance-with-modern-frameworks/*"
  to = "/2024-web-performance-with-modern-frameworks/index.html"
  status = 200

[[redirects]]
  from = "/2024-web-performance-with-nuxt/*"
  to = "/2024-web-performance-with-nuxt/index.html"
  status = 200

[[redirects]]
  from = "/2024-css-is-getting-better/*"
  to = "/2024-css-is-getting-better/index.html"
  status = 200

[[redirects]]
  from = "/2024-whats-going-on-in-unjs/*"
  to = "/2024-whats-going-on-in-unjs/index.html"
  status = 200

[[redirects]]
  from = "/2025-css-is-getting-better-for-quanti/*"
  to = "/2025-css-is-getting-better-for-quanti/index.html"
  status = 200

[[redirects]]
  from = "/2025-ai-experiments-for-quanti/*"
  to = "/2025-ai-experiments-for-quanti/index.html"
  status = 200

[[redirects]]
  from = "/2025-tailwind-4-vs-css-6/*"
  to = "/2025-tailwind-4-vs-css-6/index.html"
  status = 200

[[redirects]]
  from = "/2025-context-engineering-and-claude-code/*"
  to = "/2025-context-engineering-and-claude-code/index.html"
  status = 200
